
package:
  name: bioconductor-metaMs
  version: 1.7.0
source:
  fn: CAMERA_1.7.0.tar.gz
  url: https://bioarchive.galaxyproject.org/CAMERA_1.7.0.tar.gz
  md5: 2b928ca28bf0ec22b40a6ec61ec0be99
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biobase
    - bioconductor-CAMERA
    - 'bioconductor-xcms >=1.35'
    - 'r >=2.10'
    - r-methods
  run:
    - bioconductor-biobase
    - bioconductor-CAMERA
    - 'bioconductor-xcms >=1.35'
    - 'r >=2.10'
    - r-methods
test:
  commands:
    - '$R -e "library(''metaMS'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/metaMS.html
  license: 'GPL (>= 2)'
  summary: 'MS-based metabolomics data processing and compound annotation pipeline.'
